### ISSUE TITLE
Use BlueJeans v2

### ISSUE THREAD

**Issue by hadess** [flathub/com.bluejeans.BlueJeans#14]
v1 (which we currently use) will stop working in a week (April 1st 2020).

Version 2.1.0 is available at: https://www.bluejeans.com/downloads

**Comment by AsciiWolf** [comment]
That is really a bad news. :-( I am working on a new update since 2.0.0 was released, but it [does not work](https://github.com/flathub/com.bluejeans.BlueJeans/pull/10#issuecomment-582419802) for some reason.

**Comment by hadess** [comment]
I can't even get it working on a stock Fedora system, so it's definitely the application's problem.

**Comment by AsciiWolf** [comment]
Ah! Let's hope they will fix it soon. I have heard that there is a unreleased 2.1.1 version that should work on Fedora, but did not test it myself.

**Comment by hadess** [comment]
> Ah! Let's hope they will fix it soon. I have heard that there is a unreleased 2.1.1 version that should work on Fedora, but did not test it myself.

I mean, https://swdl.bluejeans.com/desktop-app/linux/2.1.1/BlueJeans.rpm is a valid link...

**Comment by AsciiWolf** [comment]
Thanks.

**Comment by AsciiWolf** [comment]
By the way, another thing that needs to be updated once the 2.x version is working are the screenshots.

**Comment by hadess** [comment]
2.1.1 also crashes, but my company's opened a ticket with BlueJeans about it.

**Comment by AsciiWolf** [comment]
Let's hope BlueJeans will respond soon to the ticket and release a fix. :)

**Comment by AsciiWolf** [comment]
@hadess Did BlueJeans support respond to the ticket?

**Comment by hadess** [comment]
Of course not.

**Comment by AsciiWolf** [comment]
2.1.1 is now officially available to download, but nothing changed - it is still crashing.

**Comment by joshua-stone** [comment]
It appears that Bluejeans has been updated to 2.4.0:

https://swdl.bluejeans.com/desktop-app/linux/2.4.0/BlueJeans.rpm

The native RPM seems to work on my Fedora 32 laptop. Any idea if building it as a flatpak would resolve the aforementioned audio issues?

**Comment by AsciiWolf** [comment]
Thanks, I have updated the PR. Unfortunately, BlueJeans still crashes when connecting to a meeting.
