### ISSUE TITLE
currently stale packaged app will no longer run now

### ISSUE THREAD

**Issue by sidepiece** [flathub/com.bluejeans.BlueJeans#17]
current version---
BlueJeans                                 com.bluejeans.BlueJeans                                        1.37.22                    stable            flathub            system

is now prompting for user to download an update upon launch.  whatever is attempted behind the scenes fails.

**Comment by AsciiWolf** [comment]
You're right, the 1.x version does not work anymore. :-(

So, either the Flatpak needs to be updated to 2.x (which is a problem, see #10) or removed from Flathub.

**Comment by mcatanzaro** [comment]
Since the app cannot be updated (#10) I guess it's time to remove it.

![Screenshot from 2020-09-03 09-57-44](https://user-images.githubusercontent.com/1424966/92131843-0d45a200-edcc-11ea-8230-82a6e98ffe01.png)

**Comment by AsciiWolf** [comment]
I would give it another week or two, maybe someone will come with a solution. I will also look at it again at the weekend or next week.

**Comment by sidepiece** [comment]
im looking at trying to get bluejeans-v2 running within rootless podman right now.  i assume that if i can get it to work in podman, we can get it to work in flatpak.

**Comment by AsciiWolf** [comment]
The BlueJeans app is now EOL and no longer available on Flathub. Feel free to continue your work here: #10
