### ISSUE TITLE
Video lag observed when trying Bluejeans 2.21.2.1

### ISSUE THREAD

**Issue by tpopela** [flathub/com.bluejeans.BlueJeans#19]
Trying the build from https://github.com/flathub/com.bluejeans.BlueJeans/pull/18#issuecomment-792795905 I observed a big video lag that I don't see in Firefox or Chromium when trying the meetings over bluejeans.com. The participants video is updated just every +- minute. When I look at my preview in the bottom right corner, then I can see that there's a +- 3 seconds lag as well. I have to say that audio is fine though.

This is up to date Silverblue 34.20210307.n.0 (using Wayland) on Lenovo T480s:
```
Intel® Core™ i7-8650U CPU @ 1.90GHz × 8 
Mesa Intel® UHD Graphics 620 (KBL GT2)
```

**Comment by hadess** [comment]
I believe that the problem is mostly because the Electron runtime used doesn't have support for hardware acceleration for encoding and decoding. I'll check to see whether this is due to some missing libraries or something that needs to be fixed by Bluejeans.

**Comment by hadess** [comment]
Do you still have problems with the latest version? We updated to 2.26.0.136 today, and it's been a year.

**Comment by tpopela** [comment]
I changed the laptop in the meantime and I don't use Bluejeans that much anymore - closing this. Thank you for getting back to me Bastien.
