### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.bluejeans.BlueJeans#21]
Current screenshots in AppStream metadata are still from version 1.x. ;-)

**Comment by AsciiWolf** [comment]
@hadess Could you please update the screenshots in AppData? I don't use BlueJeans anymore. Thanks!

**Comment by hadess** [comment]
Nice of you to assign this to me, but it's probably the last thing I'd ever want to spend time on, given how this Flatpak is barely limping along because BlueJeans won't fix their software.

**Comment by AsciiWolf** [comment]
Sorry. I didn't want this to look rude.
