### ISSUE TITLE
BlueJeans v2 SSO login

### ISSUE THREAD

**Issue by ephemient** [flathub/com.bluejeans.BlueJeans#22]
Hi, I'm unable to perform SSO login with the new 2.21.2.1 Flatpak. The browser redirects to a 127.0.0.1:port that is not open - using `ss -lntp` it doesn't appear as though any bluejeans processes are listening on any TCP ports.

**Comment by hadess** [comment]
I've tested this successfully.

You might want to try removing `~/.var/app/com.bluejeans.BlueJeans/.config/bluejeans-v2/` on your system, and running the test version at https://github.com/flathub/com.bluejeans.BlueJeans/issues/22

If that still fails, please post the whole output of running the tool on the command-line.

**Comment by ephemient** [comment]
I assume you meant #23?

I see that it merged, so I updated to the latest build and now SSO login works.

Thanks.
