### ISSUE TITLE
[RFE] Include Flash Player plugin in the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.bluejeans.BlueJeans#3]
Some meetings require Flash Player plugin to be installed and do not work if the plugin is not available.

![Blue Jeans - Missing Flash Player error](https://user-images.githubusercontent.com/2339930/48487080-74701c00-e81d-11e8-91e5-7d29c810e8cc.png)

**Comment by TingPing** [comment]
:nauseated_face:

**Comment by lordtaytertot** [comment]
This is affecting me too.

**Comment by AsciiWolf** [comment]
@jayjaytay Yeah, it is affecting me as well, unfortunately, I am quite busy lately and have no time to look into this. :-/

**Comment by juhp** [comment]
For Bluejeans PrimeTime?

**Comment by AsciiWolf** [comment]
Yep, for Blue Jeans PrimeTime and video sharing. :-)

**Comment by AsciiWolf** [comment]
So I tried to make this work, however I have ran into many issues including extraction of the Flash Player archive (extracted files were corrupted for some reason), forcing Blue Jeans to use Flash from non-standard path etc. Also, I think that re-distribution of the Flash Player plugin is not allowed so it would need to be added as extra data.

**Comment by devop-mmcgrath** [comment]
Ditto here, its double tricky as a more casual flatpak user because it bluejeans actually directs users to a website, gives them directions to follow (those directions work since its installed on the local machine) but then bluejeans continues to fail to function.

**Comment by juhp** [comment]
Apparently BlueJeans PrimeTime now supports html5 codecs.
Could this flatpak use the html5-codecs extension?

Edit: I just installed the FirefoxNightly flatpak for html5 video support.

**Comment by AsciiWolf** [comment]
@juhp Is it available for Linux? I see that there was no new Blue Jeans update.

**Comment by juhp** [comment]
Well it works with https://firefox-flatpak.mojefedora.cz/ without flash.

Though I would prefer not to have to rely on Firefox Nightly for BlueJeans...

**Comment by AsciiWolf** [comment]
@juhp I am not sure, but I think that the web version uses a new code based on the 2.x version, that is not yet available for Linux.

**Comment by juhp** [comment]
@AsciiWolf I am just talking about bluejeans running in browser - yes seems web version is lot newer.

**Comment by damani42** [comment]
I have the same error. Do you thinks that any chance to be fix? Or it's really complicate to fix.

**Comment by AsciiWolf** [comment]
It unfortunately seems to be a complicated fix. Let's hope the 2.x version for Linux will be released soon.

**Comment by damani42** [comment]
Ok I see. But the weird thing, if I download the rpm package from the official bluejeans website and install it, that works.

**Comment by AsciiWolf** [comment]
Hmm, do you have Flash plugin installed on your system?

**Comment by damani42** [comment]
Yes I have.

**Comment by AsciiWolf** [comment]
BlueJeans 2.0.0 was finally released today! I will update the Flatpak.

**edit:** I am having problems when trying to update to the new Blue Jeans version, see [this comment](https://github.com/flathub/com.bluejeans.BlueJeans/pull/10#issue-352925762). I will close this ticket after the issues are resolved and PR is merged.

**Comment by hadess** [comment]
Flash Player is obsolete and isn't used from Bluejeans v2 onwards.
