### ISSUE TITLE
Find a new maintainer

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.bluejeans.BlueJeans#44]
This Flatpak needs a new maintainer since I don't use it anymore and the current maintainer has stepped down.

See this issue and its comments for more details: https://github.com/flathub/flathub/issues/4330

**Comment by hadess** [comment]
FYI, don't think that find a new maintainer will be needed:
https://www.theverge.com/2023/8/8/23825112/verizon-bluejeans-shutting-down-sunset

**Comment by AsciiWolf** [comment]
Oops :-)

**Comment by hadess** [comment]
FYI https://github.com/flathub/com.bluejeans.BlueJeans/pull/45
