### ISSUE TITLE
Crash closing "Report an issue" dialogue

### ISSUE THREAD

**Issue by hadess** [flathub/com.bluejeans.BlueJeans#5]
I opened the "Report an issue" dialogue thinking I could use it to file an RFE but realised this was about reporting bugs. Closing the dialogue using the close button in the title bar crashed the application.

**Comment by AsciiWolf** [comment]
Yeah, I noticed this too. It's unfortunate and quite ironic when bug reporter is crashing, however I wasn't able to find the crash reason and how to fix it. :-(

**Comment by hadess** [comment]
I couldn't find a way to report those bugs either, and I couldn't find out why the "2.0" version of the application was unavailable on Linux (there are release notes for a beta version, but no way to download it).

**Comment by AsciiWolf** [comment]
This seems to be fixed since 2.0.0. I will close this ticket after #10 is merged.

**Comment by AsciiWolf** [comment]
Does not seem to happen anymore in 2.x.
